# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: NaClnikOnline

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Test      
      run: dotnet test
    - name: Publish
      run: dotnet publish Main/Main.csproj --configuration Release
    - name: Copy folder content recursively to remote
      uses: garygrossgarten/github-action-scp@release
      with:
        rmRemote: true
        local: /home/runner/work/NaClnikOnline/NaClnikOnline/Main/bin/Release/net6.0/publish/
        remote: /var/www/www-root/data/www/naclnik.online/
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
    - name: Restart services
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          systemctl disable kestrel-naclnik-online-watcher.service
          systemctl enable kestrel-naclnik-online-watcher.service && systemctl start kestrel-naclnik-online-watcher.service